OnlineShop/Areas/Admin/Controllers/ProductCategoryController.cs
using Model.EF;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        private OnlineShopDbContext _context;

        public ProductCategoryController()
        {
            _context = new OnlineShopDbContext();
        }

        // GET: Admin/ProductCatgrry
        public ActionResult Index()
        {
            //var dao = new ProductCategoryDao();
            //var productCategoryList = dao.ListAll();
            //return View(productCategoryList);
            return View();
        }

        [HttpGet]
        public JsonResult LoadData(int page, int pageSize=3)
        {
            var model = _context.ProductCategories.OrderByDescending(x => x.CreatedDate).ToList();
            int totalRow = model.Count();
            var productCategory = model.Skip((page - 1) * pageSize).Take(pageSize);
           
            return Json(new
            {
                status = true,
                total=totalRow,
                data = productCategory
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetDetail(int id)
        {
            var productCategory = _context.ProductCategories.Find(id);
            return Json(new
            {
                data = productCategory,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CreateUpdate(string strProductCategory)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            ProductCategory productCategory = serializer.Deserialize<ProductCategory>(strProductCategory);
            bool status = false;
            string message = string.Empty;
            if (productCategory.ID == 0)
            {
                productCategory.CreatedDate = DateTime.Now;
                _context.ProductCategories.Add(productCategory);
                try
                {
                    _context.SaveChanges();
                    status = true;
                }
                catch (Exception ex)
                {
                    status = false;
                    message = ex.Message;
                }
            }
            else
            {
                var entity = _context.ProductCategories.Find(productCategory.ID);
                entity.Name = productCategory.Name;
                entity.MetaTitle = productCategory.MetaTitle;
                entity.Status = productCategory.Status;
                entity.ModifiedDate = DateTime.Now;
                try
                {
                    _context.SaveChanges();
                    status = true;
                }
                catch (Exception ex)
                {
                    status = false;
                    message = ex.Message;
                }
            }
            return Json(new
            {
                status = status,
                message = message
            });
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var entity = _context.ProductCategories.Find(id);
            _context.ProductCategories.Remove(entity);
            try
            {
                _context.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = false,
                    message = ex.Message
                });
            }
        }
    }
}

OnlineShop/Areas/Admin/Views/ProductCategory/Create.cshtml
@model Model.EF.ProductCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section header{
    Thêm mới danh mục sản phẩm.
}
<div class="container" style="width:100%">
    @using (Html.BeginForm("Create", "ProductCategory", FormMethod.Post))
    {
        <div class="form-group row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MetaTitle,new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ParentId, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DisplayOrder, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.SeoTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SeoTitle, new { @class = "form-control" })
            </div>
        </div>
        @*<div class="form-group row">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CreatedDate, new { @class = "form-control" })
            </div>
        </div>*@
        <div class="form-group row">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ModifiedDate, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ModifieBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ModifieBy, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.MetaKeywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MetaKeywords, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.MetaDescriptions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MetaDescriptions, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Status)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ShowOnHome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.ShowOnHome)
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

OnlineShop/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<Model.EF.ProductCategory>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section header{
    Danh mục sản phẩm.
}
@section jsFooter{
    <script src="~/assets/admin/js/plugins/jquery.twbsPagination.min.js"></script>
    <script src="~/assets/admin/js/controller/productCategoryController.js"></script>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Thông tin danh mục sản phẩm.
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-lg-12">
                        <div class="col-md-4">
                            <input type="text" value="" class="form-control" name="searchString" />
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success">Tìm kiếm</button>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAddUpdate" onclick="resetForm()">Thêm mới</button>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <td><b>Tên danh mục</b></td>
                                <td><b>Tiêu đề</b></td>
                                <td><b>Người tạo</b></td>
                                <td><b>Trạng thái</b></td>
                                <td><b>Chức năng</b></td>
                            </tr>
                        </thead>
                        <tbody id="tbl-productcategory"></tbody>
                    </table>
                    <div id="pagination" class="pagination">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@RenderPage("_createUpdateProductCategory.cshtml")

OnlineShop/Areas/Admin/Views/ProductCategory/_createUpdateProductCategory.cshtml
<div class="modal" id="modalAddUpdate" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><b>Add/Update product category</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label for="txtName" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtName" placeholder="name">
                            <input type="hidden" id="hidID" value="0" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtMetaTitle" class="col-sm-2 col-form-label">MetaTitle</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtMetaTitle" placeholder="metatitle">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtCreatedBy" class="col-sm-2 col-form-label">CreatedBy</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtCreatedBy" placeholder="createdBy">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="ckStatus" class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="ckStatus">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="btnSave" onclick="createUpdate()">Save</button>
            </div>
        </div>
    </div>
</div>